import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Nav } from "@/components/nav";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <Nav />
      <div className="max-w-3xl mx-auto px-6 pt-28 pb-20">
        <Link href="/">
          <button className="flex items-center gap-1.5 text-muted-foreground hover:text-foreground transition-colors text-sm mb-10">
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
        </Link>

        <h1 className="font-serif text-5xl font-light text-foreground mb-2 tracking-wide">Terms of Service</h1>
        <p className="text-muted-foreground text-sm mb-12">Last updated: March 2026</p>

        <div className="space-y-10">
          {[
            {
              title: "1. Acceptance of Terms",
              body: "By accessing or using Wandr, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our service. We reserve the right to update these terms at any time, and continued use of the platform following any changes constitutes your acceptance of the revised terms.",
            },
            {
              title: "2. Use of the Service",
              body: "Wandr provides AI-assisted travel planning and itinerary generation for personal, non-commercial use. You agree to use the platform only for lawful purposes, and not to misuse, reverse-engineer, or interfere with the service. You are responsible for maintaining the confidentiality of your account credentials.",
            },
            {
              title: "3. Account Registration",
              body: "To access certain features, you may be required to create an account. You agree to provide accurate, current, and complete information, and to update your information as necessary. You are responsible for all activity that occurs under your account.",
            },
            {
              title: "4. Itinerary & Recommendations",
              body: "All itineraries and recommendations generated by Wandr are for informational and planning purposes only. While we strive for accuracy and quality, we do not guarantee the availability, pricing, or quality of any third-party venues, services, or experiences recommended. Always confirm bookings directly with providers.",
            },
            {
              title: "5. Intellectual Property",
              body: "The Wandr name, logo, platform design, and original content are the intellectual property of Wandr and may not be reproduced or used without prior written permission. Itineraries generated for personal use may be shared freely, provided they are attributed to Wandr.",
            },
            {
              title: "6. Limitation of Liability",
              body: "Wandr is provided on an 'as is' basis. To the maximum extent permitted by law, Wandr shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to travel disruptions, booking errors, or reliance on recommendations.",
            },
            {
              title: "7. Termination",
              body: "We reserve the right to suspend or terminate your access to Wandr at any time, with or without cause, at our sole discretion. You may also close your account at any time by contacting us at support@wandr.app.",
            },
            {
              title: "8. Governing Law",
              body: "These Terms are governed by and construed in accordance with the laws of the Province of British Columbia, Canada, without regard to conflict of law principles.",
            },
            {
              title: "9. Contact",
              body: "For questions about these Terms, please contact us at legal@wandr.app.",
            },
          ].map((section) => (
            <div key={section.title}>
              <h2 className="font-serif text-2xl font-light text-foreground mb-3 tracking-wide">{section.title}</h2>
              <p className="text-muted-foreground leading-relaxed text-[15px]">{section.body}</p>
            </div>
          ))}
        </div>
      </div>

      <footer className="py-8 px-6 border-t border-border">
        <div className="max-w-3xl mx-auto flex items-center justify-between gap-4 text-xs text-muted-foreground">
          <span className="font-serif text-base font-light tracking-widest text-foreground">Wandr</span>
          <div className="flex items-center gap-5">
            <Link href="/privacy"><span className="hover:text-foreground transition-colors cursor-pointer">Privacy</span></Link>
            <Link href="/terms"><span className="hover:text-foreground transition-colors cursor-pointer">Terms</span></Link>
            <Link href="/contact"><span className="hover:text-foreground transition-colors cursor-pointer">Contact</span></Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
