import ical, { ICalCalendarMethod } from "ical-generator";

// ─── Types ─────────────────────────────────────────────────────────────────────

interface ActivityBlock {
  id: string;
  timeSlot: "morning" | "afternoon" | "evening" | "rest";
  primary: {
    name: string;
    type?: string;
    description?: string;
    whyForYou?: string;
    costRange?: string;
    address?: string;
    lat?: number;
    lng?: number;
  };
}

interface ItineraryDay {
  dayNumber: number;
  date: string;
  blocks: ActivityBlock[];
}

interface ItineraryData {
  destination: string;
  country?: string;
  durationDays: number;
  days: ItineraryDay[];
}

// ─── Time slot → start hour ───────────────────────────────────────────────────

const SLOT_HOUR: Record<string, number> = {
  morning:   9,
  afternoon: 13,
  evening:   19,
  rest:      12,
};

const SLOT_DURATION_HOURS: Record<string, number> = {
  morning:   3,
  afternoon: 4,
  evening:   3,
  rest:      2,
};

// ─── Main export function ──────────────────────────────────────────────────────

export function generateIcal(itinerary: ItineraryData): string {
  const cal = ical({
    name: `Wandr — ${itinerary.destination}`,
    description: `Your Wandr itinerary for ${itinerary.destination}${itinerary.country ? `, ${itinerary.country}` : ""}`,
    method: ICalCalendarMethod.PUBLISH,
    prodId: { company: "Wandr", product: "Itinerary" },
  });

  for (const day of itinerary.days) {
    for (const block of day.blocks) {
      if (block.timeSlot === "rest") continue; // skip rest blocks

      const startHour    = SLOT_HOUR[block.timeSlot] ?? 9;
      const durationHrs  = SLOT_DURATION_HOURS[block.timeSlot] ?? 2;

      const start = new Date(`${day.date}T${String(startHour).padStart(2, "0")}:00:00`);
      const end   = new Date(start.getTime() + durationHrs * 60 * 60 * 1000);

      const descParts = [
        block.primary.description,
        block.primary.whyForYou ? `✦ Why we picked this: ${block.primary.whyForYou}` : null,
        block.primary.costRange ? `💰 ${block.primary.costRange}` : null,
        block.primary.type      ? `🏷 ${block.primary.type}` : null,
        "\nGenerated by Wandr",
      ].filter(Boolean).join("\n\n");

      cal.createEvent({
        id:          block.id,
        summary:     block.primary.name,
        description: descParts,
        location:    block.primary.address ?? itinerary.destination,
        start,
        end,
        url:         block.primary.lat && block.primary.lng
          ? `https://www.google.com/maps?q=${block.primary.lat},${block.primary.lng}`
          : undefined,
      });
    }
  }

  return cal.toString();
}
